### PR TITLE
get closer to working docs

### PR DESCRIPTION
**Pull request by visr**
Docs were not building on Documenter 1 due to the repo link, but this doesn't seem needed, since the GitHub link in the rendered docs points to the right location.

This removes the accidentally committed docs/build, and updates .gitignore to ensure that won't happen again.

Updated the "Manual test" code and made sure it is working.

### CODE REVIEW

**Comment by visr** [comment]
This image from the docs still seems to give issues. Perhaps we can just load it from here and remove it from the repo:

example-fs8

**Comment by visr** [comment]
Just noticed that getting this all working again is more that I have time for right now. I see there is #13 open for it as well. Shall we just get this in, since it does get us closer?

**Comment by rafaqz** [comment]
Im not sure if Leaflet even works anymore, as WebIO.jl is kind of abandoned.

**Comment by visr** [comment]
Yeah I tried this manual test from runtests and that seemed to work well.

**Review by rafaqz — APPROVED** [review]

**Comment by rafaqz** [comment]
Ugh damn the docs were actually broken, maybe In misunderstood your "shall we just get this in" comment

**Pull request merged**
